" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'slim-template/vim-slim'
Plugin 'kien/ctrlp.vim'
call vundle#end()

filetype plugin indent on

set tabstop=2
set shiftwidth=2
set expandtab
set number
set noswapfile

syntax enable

" Set Gemfile as ruby file
autocmd BufNewFile,BufRead Gemfile set syntax=ruby

" Searching
set hlsearch    " Set highlight search
set incsearch   " Set searchs dynamic
set ignorecase  " case insensitive search
set smartcase   " for capital letter

" Maps
nnoremap <F1> 1gt
nnoremap <F2> 2gt
nnoremap <F3> 3gt
nnoremap <F4> 4gt
nnoremap <F5> 5gt
nnoremap <F6> 6gt
nnoremap <PageUp> gt
nnoremap <PageDown> gT

" Colors
set t_Co=256
set t_ut=
let g:solarized_termtrans = 1
let g:solarized_termcolors = 16
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
set background=dark
colorscheme solarized
